spring.application.name=finc2u-app
# Configurações do H2 em arquivo (persistência entre reinicializações)
spring.datasource.url=jdbc:h2:file:./dados/finc2udb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Habilitar o console do H2 para debug (acesso no navegador via /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Configurações do Hibernate/JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true